### PR TITLE
support multiple hw ids and updater ids per updater

### LINKED ISSUE #16: Support multiple HW id per updater
As a user, I'd like to be able to utilize the same updater to send information from different hardware devices.

As a use case, I have a board that collects information coming in from N different peripherals devices. This board is my micro-ROS client and runs a diagnostic_updater. Each peripheral may have up to M valuable information I may want to report up. Thus, I'd like to be able to also indicate to what HW_id a task belongs.

Does this use case make sense?

### PR DESCRIPTION
**Pull request by bjv-capra**
This PR resolves #16

### CODE REVIEW

**Comment by bjv-capra** [comment]
I didn't want to remove the updater_id from the updater struct. But at the same time, there's nothing setting it up. So I didn't know what to do with it ATM.

**Comment by bjv-capra** [comment]
@norro friendly ping. Thoughts?

**Comment by norro** [comment]
Sorry @bjv-capra, I am pretty swampedright now. I will have a look at it in the afternoon or beginning of next week.

**Review by norro — CHANGES_REQUESTED** [review]
It took me a bit, because I wanted to understand that this PR is still allowing to emulate the current setup. For this I created ran the entire pipeline from example updaters to bridge to aggregator to robot monitor (sort of what I suggest to do automatically in #28).

All in all the PR looks good to me. It seems that just the example updaters (`MICRO_ROS_DIAGNOSTIC_UPDATER_EXAMPLES=True`) and a bit of documentation is necessary.

Thank you for the suggestion and implementation. :)

**Comment by bjv-capra** [comment]
Regarding the examples, why would we enable them by default? I'll see to update the documentation.

**Comment by norro** [comment]
Oh, sorry, I didn't mean to make them default, just to update them. Currently, they don't build properly in this PR, _if_ someone would enable them.

**Comment by bjv-capra** [comment]
Got it, I'll update them and update the PR.

**Comment by bjv-capra** [comment]
Just FYI, while updating the PR I noticed that the system default QoS drops messages. I couldn't quite find the default values of the struct, but I guess it's volatile. I changed it to be reliable and keep_last(10).

I  also refactored the examples a bit, I still need to update the Readme

**Comment by norro** [comment]
Agreed, the default QoS does not seem to be appropriate.
Off-topic: I wonder if we would want to suggest a diagnostics default QoS. Currently there is just default, service, sensor, parameter, [see ](https://docs.ros.org/en/rolling/Concepts/About-Quality-of-Service-Settings.html).

**Comment by bjv-capra** [comment]
@norro Any clue why the pipeline fails to build? It says it doesn't know `rclc_publisher_init_default` which is odd...

Off-topic, wouldn't be a bad idea, as diagnostics is quite a widely used feature.

**Comment by norro** [comment]
I can reproduce this error in my lcoal setup, but don't really understand this either. The symbol `rclc_publisher_init_default` _is_ contained in the rclc library, that I can see.

**Comment by bjv-capra** [comment]
Seems I was running with an old version of galactic. I updated it and I do get the same error now. But I don't quite understand why. Do I need to build rclc from source?

**Comment by bjv-capra** [comment]
I think I found a possible fix

**Comment by bjv-capra** [comment]
@norro  this is ready now

**Review by norro — APPROVED** [review]
Thank for the PR, @bjv-capra. I think diagnostics get more suitable for micro controllers now with these changes.

**Comment by norro** [comment]
@bjv-capra Just seconds before your merge, I realized that you forgot to sign your commits, which is part of our contribution guideline (see https://github.com/micro-ROS/micro_ros_diagnostics/blob/master/CONTRIBUTING.md#sign-your-work).
Can you sign your latest commits and force-push them to master, please?

I added the DCO check to the PR checks now for the future.

**Comment by bjv-capra** [comment]
I tried to force-push and got
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "build (ubuntu-20.04, rolling)" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:micro-ROS/micro_ros_diagnostics.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:micro-ROS/micro_ros_diagnostics.git'
```

**Pull request merged**
